[build]
  publish = "."  # or wherever your HTML files are

[[headers]]
  for = "/content/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "application/json"