backend:
  name: git-gateway
  branch: main

media_folder: "assets/imgs"
public_folder: "/assets/imgs"

collections:
  # Homepage Contents
  - name: "homepage"
    label: "Homepage"
    files:
      - label: "Homepage Content"
        name: "homepage"
        file: "index.html"
        fields:
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Hero Label", name: "hero_label", widget: "string", default: "ABOUT US" }
              - { label: "Hero Title", name: "hero_title", widget: "text", default: "Florida Plumbing, Sewer & Drain Services Since 1987" }
              - { label: "Hero Description", name: "hero_description", widget: "text" }
              - { label: "Years in Business", name: "years_stat", widget: "number", default: 37 }
              - { label: "Hero Image", name: "hero_image", widget: "image", default: "/assets/imgs/van.png" }
          - label: "Service Areas Section"
            name: "service_areas"
            widget: "object"
            fields:
              - { label: "Section Label", name: "section_label", widget: "string", default: "SERVICE AREAS" }
              - { label: "Section Title", name: "section_title", widget: "string", default: "Serving Florida With Superior Service" }
              - { label: "Section Description", name: "section_description", widget: "text" }
              - { label: "Service Map Image", name: "map_image", widget: "image", default: "/assets/imgs/service-map.jpg" }
          - label: "Services Section"
            name: "services"
            widget: "object"
            fields:
              - { label: "Section Label", name: "section_label", widget: "string", default: "WHAT WE DO" }
              - { label: "Section Title", name: "section_title", widget: "string", default: "We're The Experts Florida Trusts" }
              - { label: "Section Description", name: "section_description", widget: "text" }
          - label: "Contact Information"
            name: "contact"
            widget: "object"
            fields:
              - { label: "Emergency Phone", name: "emergency_phone", widget: "string", default: "(866) 374-0402" }
              - { label: "Main Phone", name: "main_phone", widget: "string", default: "(813) 378-3882" }
              - { label: "Address", name: "address", widget: "text", default: "1821 36th Street SE, Ruskin, FL 33570" }

  # About Us Page
  - name: "about"
    label: "About Us Page"
    files:
      - label: "About Us Content"
        name: "about"
        file: "assets/html/about-us.html"
        fields:
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Hero Label", name: "hero_label", widget: "string", default: "ABOUT US" }
              - { label: "Hero Title", name: "hero_title", widget: "text" }
              - { label: "Background Image", name: "background_image", widget: "image", default: "/assets/imgs/team-background.jpg" }
          - label: "About Content"
            name: "content"
            widget: "object"
            fields:
              - { label: "Main Title", name: "main_title", widget: "text" }
              - { label: "Paragraph 1", name: "paragraph_1", widget: "text" }
              - { label: "Paragraph 2", name: "paragraph_2", widget: "text" }
              - { label: "Paragraph 3", name: "paragraph_3", widget: "text" }

  # Contact Page
  - name: "contact"
    label: "Contact Page"
    files:
      - label: "Contact Content"
        name: "contact"
        file: "assets/html/contact.html"
        fields:
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Hero Label", name: "hero_label", widget: "string", default: "CONTACT" }
              - { label: "Hero Title", name: "hero_title", widget: "text" }
              - { label: "Background Image", name: "background_image", widget: "image", default: "/assets/imgs/contact-background.jpg" }
          - label: "Contact Information"
            name: "contact_info"
            widget: "object"
            fields:
              - { label: "Main Title", name: "main_title", widget: "string", default: "We're Here For You Florida." }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Service Areas Title", name: "areas_title", widget: "string", default: "Area We Serve." }
              - { label: "Service Areas List", name: "service_areas", widget: "text" }

  # Plumbing Services Page
  - name: "plumbing"
    label: "Plumbing Services"
    files:
      - label: "Plumbing Content"
        name: "plumbing"
        file: "assets/html/plumbing.html"
        fields:
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Hero Label", name: "hero_label", widget: "string", default: "COMMERCIAL PLUMBING" }
              - { label: "Hero Title", name: "hero_title", widget: "text" }
              - { label: "Background Image", name: "background_image", widget: "image", default: "/assets/imgs/commercial-plumbing-hero.jpg" }
          - label: "Services Overview"
            name: "services_overview"
            widget: "object"
            fields:
              - { label: "Section Label", name: "section_label", widget: "string", default: "WHAT WE DO" }
              - { label: "Section Title", name: "section_title", widget: "text" }
              - { label: "Section Description", name: "section_description", widget: "text" }
              - { label: "Services Image", name: "services_image", widget: "image", default: "/assets/imgs/commercial-plumbing.jpg" }
          - label: "Main Content"
            name: "main_content"
            widget: "object"
            fields:
              - { label: "Content Title", name: "content_title", widget: "text" }
              - { label: "Paragraph 1", name: "paragraph_1", widget: "text" }
              - { label: "Paragraph 2", name: "paragraph_2", widget: "text" }
              - { label: "Paragraph 3", name: "paragraph_3", widget: "text" }

  # Sewer Services Page
  - name: "sewer_services"
    label: "Sewer Services"
    files:
      - label: "Sewer Services Content"
        name: "sewer_services"
        file: "assets/html/sewer-services.html"
        fields:
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Hero Label", name: "hero_label", widget: "string", default: "SEWER SERVICES" }
              - { label: "Hero Title", name: "hero_title", widget: "text" }
              - { label: "Background Image", name: "background_image", widget: "image", default: "/assets/imgs/sewer-services-hero.jpg" }
          - label: "Services Overview"
            name: "services_overview"
            widget: "object"
            fields:
              - { label: "Section Label", name: "section_label", widget: "string", default: "WHAT WE DO" }
              - { label: "Section Title", name: "section_title", widget: "text" }
              - { label: "Section Description", name: "section_description", widget: "text" }
              - { label: "Overview Image", name: "overview_image", widget: "image", default: "/assets/imgs/sewer-services-overview.jpg" }
          - label: "Main Content"
            name: "main_content"
            widget: "object"
            fields:
              - { label: "Content Title", name: "content_title", widget: "text" }
              - { label: "Paragraph 1", name: "paragraph_1", widget: "text" }
              - { label: "Paragraph 2", name: "paragraph_2", widget: "text" }
              - { label: "Paragraph 3", name: "paragraph_3", widget: "text" }

  # Drain Services Page
  - name: "drain_services"
    label: "Drain Services"
    files:
      - label: "Drain Services Content"
        name: "drain_services"
        file: "assets/html/drain-services.html"
        fields:
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Hero Label", name: "hero_label", widget: "string", default: "DRAIN SERVICES" }
              - { label: "Hero Title", name: "hero_title", widget: "text" }
              - { label: "Background Image", name: "background_image", widget: "image", default: "/assets/imgs/drain-services-hero.jpg" }
          - label: "Services Overview"
            name: "services_overview"
            widget: "object"
            fields:
              - { label: "Section Label", name: "section_label", widget: "string", default: "WHAT WE DO" }
              - { label: "Section Title", name: "section_title", widget: "text" }
              - { label: "Section Description", name: "section_description", widget: "text" }
              - { label: "Overview Image", name: "overview_image", widget: "image", default: "/assets/imgs/drain-cleaning.jpg" }
          - label: "Main Content"
            name: "main_content"
            widget: "object"
            fields:
              - { label: "Content Title", name: "content_title", widget: "text" }
              - { label: "Paragraph 1", name: "paragraph_1", widget: "text" }
              - { label: "Paragraph 2", name: "paragraph_2", widget: "text" }
              - { label: "Paragraph 3", name: "paragraph_3", widget: "text" }

  # Sewer & Drain Combined Page
  - name: "sewer_drain"
    label: "Sewer & Drain Page"
    files:
      - label: "Sewer & Drain Content"
        name: "sewer_drain"
        file: "assets/html/sewer-drain..html"
        fields:
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Hero Label", name: "hero_label", widget: "string", default: "SEWER & DRAIN SERVICES" }
              - { label: "Hero Title", name: "hero_title", widget: "text" }
              - { label: "Background Image", name: "background_image", widget: "image", default: "/assets/imgs/sewer-drain-hero.jpg" }
          - label: "Services Overview"
            name: "services_overview"
            widget: "object"
            fields:
              - { label: "Section Label", name: "section_label", widget: "string", default: "WHAT WE DO" }
              - { label: "Section Title", name: "section_title", widget: "text" }
              - { label: "Section Description", name: "section_description", widget: "text" }
              - { label: "Overview Image", name: "overview_image", widget: "image", default: "/assets/imgs/sewer-drain-overview.jpg" }
          - label: "Main Content"
            name: "main_content"
            widget: "object"
            fields:
              - { label: "Content Title", name: "content_title", widget: "text" }
              - { label: "Paragraph 1", name: "paragraph_1", widget: "text" }
              - { label: "Paragraph 2", name: "paragraph_2", widget: "text" }
              - { label: "Paragraph 3", name: "paragraph_3", widget: "text" }

  # Global Settings
  - name: "settings"
    label: "Global Settings"
    files:
      - label: "Site Settings"
        name: "site_settings"
        file: "_data/settings.yml"
        fields:
          - { label: "Site Title", name: "site_title", widget: "string", default: "American Gulf Plumbing" }
          - { label: "Site Description", name: "site_description", widget: "text" }
          - { label: "Company Tagline", name: "tagline", widget: "string", default: "Nobody wows clients like we do." }
          - label: "Contact Information"
            name: "contact"
            widget: "object"
            fields:
              - { label: "Emergency Phone", name: "emergency_phone", widget: "string" }
              - { label: "Main Phone", name: "main_phone", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
              - { label: "Address", name: "address", widget: "text" }
              - { label: "Business Hours", name: "hours", widget: "text" }
          - label: "Social Media"
            name: "social"
            widget: "object"
            fields:
              - { label: "Facebook URL", name: "facebook", widget: "string" }
              - { label: "Instagram URL", name: "instagram", widget: "string" }
              - { label: "LinkedIn URL", name: "linkedin", widget: "string" }
          - label: "Logo & Branding"
            name: "branding"
            widget: "object"
            fields:
              - { label: "Main Logo", name: "main_logo", widget: "image" }
              - { label: "Footer Logo", name: "footer_logo", widget: "image" }