backend:
  name: git-gateway
  branch: main

media_folder: "assets/imgs"
public_folder: "/assets/imgs"

collections:
  # Content Data Files (JSON format for easy JavaScript loading)
  - name: "content"
    label: "Website Content"
    files:
      - label: "Homepage Content"
        name: "homepage"
        file: "content/homepage.json"
        fields:
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Hero Label", name: "label", widget: "string", default: "ABOUT US" }
              - { label: "Hero Title", name: "title", widget: "text", default: "Florida Plumbing, Sewer & Drain Services Since 1987" }
              - { label: "Hero Description", name: "description", widget: "text", default: "American Gulf Plumbing (AGP) focus on commercial, industrial, and governmental plumbing, specializing in the complex, large-scale demands of these sectors, delivering sustained solutions that keep operations running." }
              - { label: "Years in Business", name: "years", widget: "number", default: 37 }
              - { label: "Hero Image", name: "image", widget: "image", default: "/assets/imgs/van.png" }
          - label: "Service Areas"
            name: "service_areas"
            widget: "object"
            fields:
              - { label: "Section Label", name: "label", widget: "string", default: "SERVICE AREAS" }
              - { label: "Section Title", name: "title", widget: "string", default: "Serving Florida With Superior Service" }
              - { label: "Description", name: "description", widget: "text", default: "our team of dispatchers and fleet of fully-stocked trucks allow us to serve homeowners throughout the greater Florida" }
              - { label: "Map Image", name: "image", widget: "image", default: "/assets/imgs/service-map.jpg" }
          - label: "Services Section"
            name: "services"
            widget: "object"
            fields:
              - { label: "Section Label", name: "label", widget: "string", default: "WHAT WE DO" }
              - { label: "Section Title", name: "title", widget: "string", default: "We're The Experts Florida Trusts" }
              - { label: "Description", name: "description", widget: "text", default: "If you need expert plumbing services in Florida, join the growing number of satisfied clients that have experienced our exceptional service for over 37 years." }

      - label: "About Us Content"
        name: "about"
        file: "content/about.json"
        fields:
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Hero Label", name: "label", widget: "string", default: "ABOUT US" }
              - { label: "Hero Title", name: "title", widget: "text", default: "Your Trusted Florida Plumbing, Sewer & Drain Experts" }
              - { label: "Background Image", name: "image", widget: "image", default: "/assets/imgs/team-background.jpg" }
          - label: "About Content"
            name: "content"
            widget: "object"
            fields:
              - { label: "Main Title", name: "title", widget: "text", default: "Lead with AGP — Florida's Full-Service Plumbing Partner Backed by Apollo's 37 Years of Trust" }
              - { label: "Paragraph 1", name: "paragraph1", widget: "text" }
              - { label: "Paragraph 2", name: "paragraph2", widget: "text" }
              - { label: "Paragraph 3", name: "paragraph3", widget: "text" }

      - label: "Contact Information"
        name: "contact"
        file: "content/contact.json"
        fields:
          - { label: "Emergency Phone", name: "emergency_phone", widget: "string", default: "(866) 374-0402" }
          - { label: "Main Phone", name: "main_phone", widget: "string", default: "(813) 378-3882" }
          - { label: "Email", name: "email", widget: "string", default: "info@americangulfplumbing.com" }
          - { label: "Address Line 1", name: "address1", widget: "string", default: "1821 36th Street SE" }
          - { label: "Address Line 2", name: "address2", widget: "string", default: "Ruskin, FL 33570" }
          - { label: "Business Hours", name: "hours", widget: "string", default: "Monday - Friday: 7am - 4pm" }
          - { label: "Emergency Hours", name: "emergency_hours", widget: "string", default: "Emergency Services Available During Operating Hours" }

      - label: "Service Pages"
        name: "services"
        file: "content/services.json"
        fields:
          - label: "Plumbing Services"
            name: "plumbing"
            widget: "object"
            fields:
              - { label: "Hero Title", name: "hero_title", widget: "text", default: "Florida's Full-Service Plumbing Partner, backed by Apollo's 37 Years of trust" }
              - { label: "Main Title", name: "main_title", widget: "text", default: "Lead with AGP — Florida's Full-Service Plumbing Partner" }
              - { label: "Description", name: "description", widget: "text" }
          - label: "Sewer Services"
            name: "sewer"
            widget: "object"
            fields:
              - { label: "Hero Title", name: "hero_title", widget: "text", default: "Florida's Full-Service Plumbing Partner, backed by Apollo's 37 Years of trust" }
              - { label: "Main Title", name: "main_title", widget: "text", default: "Expert Sewer Systems Built for Florida's Toughest Environments" }
              - { label: "Description", name: "description", widget: "text" }
          - label: "Drain Services"
            name: "drain"
            widget: "object"
            fields:
              - { label: "Hero Title", name: "hero_title", widget: "text", default: "Florida's Full-Service Plumbing Partner, backed by Apollo's 37 Years of trust" }
              - { label: "Main Title", name: "main_title", widget: "text", default: "Reliable Drain Services for Florida's Demanding Facilities" }
              - { label: "Description", name: "description", widget: "text" }

  # Media/Images Management
  - name: "media"
    label: "Website Images"
    files:
      - label: "Website Images"
        name: "images"
        file: "content/images.json"
        fields:
          - { label: "Main Logo", name: "main_logo", widget: "image", default: "/assets/imgs/AGP-logo.png" }
          - { label: "Footer Logo", name: "footer_logo", widget: "image", default: "/assets/imgs/AGP-logo-no-title.png" }
          - { label: "Hero Van Image", name: "hero_van", widget: "image", default: "/assets/imgs/van.png" }
          - { label: "Service Map", name: "service_map", widget: "image", default: "/assets/imgs/service-map.jpg" }
          - { label: "Team Background", name: "team_bg", widget: "image", default: "/assets/imgs/team-background.jpg" }
          - { label: "Contact Background", name: "contact_bg", widget: "image", default: "/assets/imgs/contact-background.jpg" }
          - { label: "Plumbing Hero Background", name: "plumbing_bg", widget: "image", default: "/assets/imgs/commercial-plumbing-hero.jpg" }
          - { label: "Commercial Plumbing Image", name: "commercial_plumbing", widget: "image", default: "/assets/imgs/commercial-plumbing.jpg" }

  # Social Media Links
  - name: "social"
    label: "Social Media"
    files:
      - label: "Social Media Links"
        name: "social_links"
        file: "content/social.json"
        fields:
          - { label: "Facebook URL", name: "facebook", widget: "string", default: "https://www.facebook.com/AmericanGulfPlumbing" }
          - { label: "Instagram URL", name: "instagram", widget: "string", default: "https://www.instagram.com/americangulfplumbing" }
          - { label: "LinkedIn URL", name: "linkedin", widget: "string", default: "" }

          